### ISSUE TITLE
Mismatched dependencies in busted-2.0.rc12-0.rockspec

### ISSUE THREAD

**Issue by david-dever-23-box** [Olivine-Labs/busted#520] opened 2016-05-25 12:14 UTC
Please verify the base version dependencies before publishing the versioned (non-scm) rockspec - fails to run due to mis-matched **lua_cliargs** (must be `2.5-5` due to API changes) as well as (intentionally deprecated dependency on) **luasocket** with the internally set version, `2.0.rc11-0` (also mismatched to spec version). 

```
busted/modules/cli.lua:111: attempt to call method 'add_flag' (a nil value)
```

This has broken our continuous integration overnight and I've had to peg these until this is updated.

Thanks - it's likely an honest mistake :)

**Comment by mfich** [comment] 2016-05-25 14:39
I'm encountering the same issue this morning as well.

**Comment by daurnimator** [comment] 2016-05-25 14:58
I'm also getting this (though with the rc11 rockspec). See https://travis-ci.org/daurnimator/lua-http/jobs/132782969

**Comment by ajacksified** [comment] 2016-05-25 15:24
_sigh_, sorry, completely spaced out on that. I released `2.0.rc12-1` just now which fixes that. cliargs is _correctly_ `3.0-1` now as of https://github.com/Olivine-Labs/busted/pull/458/files.

**Comment by alexsergeyev** [comment] 2016-05-25 15:51
Get an issue with latest one
Installing of travis failed with
Error: Directory busted-2.0.rc12-1 not found inside archive v2.0.rc12-1.tar.gz
```
Lua 5.2.4
Luarocks 2.3.0
```

**Comment by ajacksified** [comment] 2016-05-25 17:07
@alexsergeyev hmm, I see this:

```
luarocks install busted
Installing https://luarocks.org/busted-2.0.rc12-1.rockspec...
Using https://luarocks.org/busted-2.0.rc12-1.rockspec... switching to 'build' mode
Updating manifest for /usr/local/lib/luarocks/rocks-5.2
busted 2.0.rc12-1 is now built and installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)
```

```
Lua 5.2.4
Luarocks 2.3.0
```

Maybe the rock cache hadn't updated yet? Try again.

**Comment by DorianGray** [comment] 2016-06-14 18:11
@alexsergeyev did this start working on it's own or is it still broken?

**Comment by fasterthanlime** [comment] 2016-08-04 09:38
Not sure if related, but I'm seeing the rockspec refer to a non-existent file (`standalone_loader`):

```
$ luarocks install --verbose --local https://raw.githubusercontent.com/Olivine-Labs/busted/master/busted-2.0.rc12-1.rockspec
Using https://raw.githubusercontent.com/Olivine-Labs/busted/master/busted-2.0.rc12-1.rockspec... switching to 'build' mode

os.execute:     gunzip -c v2.0.rc12-1.tar.gz|tar -xf -
Results: 1
  1 (number): 0

Error: Build error: Failed installing busted/modules/standalone_loader.lua in /home/vagrant/.luarocks/lib/luarocks/rocks-5.1/busted/2.0.rc12-1/lua/busted/modules/standalone_loader.lua
```

**Comment by houqp** [comment] 2016-08-09 08:36
Our CI is also broken because of this. This seems like an easy bug that can be caught by busted's own CI. I remember something similar has happened couple months ago too. Given how critical busted is to the Lua community, is there any plan create a test case to catch similar issues in the future?

**Comment by DorianGray** [comment] 2016-08-09 18:43
No plan as I can't reproduce the issue. Mind making a PR?

**Comment by houqp** [comment] 2016-08-10 07:51
Sorry, I was referring to version `2.0.rc11-0`.  I can reproduce with the following travis setup:

```
git clone https://github.com/torch/luajit-rocks.git                                                                                                                      
pushd luajit-rocks                                                                                                                                                       
    git checkout 6529891                                                                                                                                                 
    cmake . -DWITH_LUAJIT21=ON -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install                                                                                        
    make install                                                                                                                                                         
popd                                                                                                                                                                     
                                                                                                                                                                          
mkdir $HOME/.luarocks                                                                                                                                                    
cp ${TRAVIS_BUILD_DIR}/install/etc/luarocks/config.lua $HOME/.luarocks/config.lua                                                                                        
echo "wrap_bin_scripts = false" >> $HOME/.luarocks/config.lua
luarocks --local install busted 2.0.rc11-0
luajit /home/travis/.luarocks/bin/busted
```

However, what I don't understand is 2.0.rc11-0 was working fine for us for a long time. It just started failing couple days ago. I am not familiar with how luarocks manages dependencies. Did lua_cliargs break the API between version `>= 2.5-0, < 3.0.rc-1`?

**Comment by fasterthanlime** [comment] 2016-08-10 09:58
Just

```bash
luarocks install --local https://raw.githubusercontent.com/Olivine-Labs/busted/master/busted-2.0.rc12-1.rockspec
```

is enough for me to reproduce. Since the archive generated by GitHub doesn't change for the `2.0.rc12-1` tag (if the tag wasn't overwritten), maybe the rockspec was changed? It refers to `busted/modules/standalone_loader.lua` which is definitely not in the archive.

**Comment by DorianGray** [comment] 2016-08-10 20:21
Yes, they did break the API and we had a problem with not pinning the dependency properly. It was resolved in the latest rc.

**Closed** 2016-11-07 19:53 UTC
