### ISSUE TITLE
random segfault when running with luajit

### ISSUE THREAD

**Issue by houqp** [Olivine-Labs/busted#496] opened 2016-02-22 00:44 UTC
Hi,

We have been having this issue for awhile. 90% of the time, it segfaults at the end of the test, inside luajit's lua_close function (most of the time it dies at `lj_gc_freeall`). It kind smells like a race condition. Does busted do multi-threading at all?

**Comment by mpeterv** [comment] 2016-02-22 12:04
Reduced testsuite reproducing the issue: put this into spec/1_spec.lua and spec/2_spec.lua, run busted spec.

```lua
for i = 1, 1000 do
  loadstring([[
    for j = 1, 20 do
      local x = {0LL}
    end
  ]])()
end
```

**Comment by houqp** [comment] 2016-02-22 18:35
Interesting, It could be a bug in LuaJIT. But we have been running the same code on many real devices for a long time any never ran into this issue. It only happens quiet frequently when running with busted.

**Comment by Tieske** [comment] 2016-02-23 22:14
we have seen this as well on Travis and CircleCI, where tests crashed at the end (busted with LuaJit). Probably warrants a bug report...

**Comment by houqp** [comment] 2016-02-26 18:03
Sometimes the tests even crash during the execution. But this happens way less frequent.

**Comment by vsergeev** [comment] 2016-02-27 00:26
:+1: I am experiencing this issue as well. In my case it occurs maybe 20% of the time.

**Comment by Tieske** [comment] 2016-02-27 22:40
did someone report this on the LuaJit mailing list?

**Comment by houqp** [comment] 2016-02-28 00:28
I can report it to the list. @Tieske , just to confirm, busted is not doing multi-threading right?

**Comment by Tieske** [comment] 2016-02-28 21:32
No, it isn't. Please do report, otherwise I will, just wanted to make sure we don't report it multiple times.

**Comment by houqp** [comment] 2016-02-29 01:57
I have sent the report to the mailing list.

**Comment by Tieske** [comment] 2016-02-29 06:34
:+1: 

For the record, the reported issue; http://www.freelists.org/post/luajit/random-segfaults-when-running-tests-with-busted

**Comment by mpeterv** [comment] 2016-02-29 09:10
Actually, given that I can reproduce the issue with busted 2.0.rc7 but not 2.0.rc6 this could be an issue in lua-term, a C dependency added in rc7.

**Comment by mpeterv** [comment] 2016-02-29 09:21
Nevermind, segfault is introduced in @b3993e6.

**Comment by houqp** [comment] 2016-03-01 08:11
@mpeterv what version of luajit are you using?

**Comment by mpeterv** [comment] 2016-03-01 09:51
@houqp I reproduced the issue using busted with testcase I posted above with luajit 2.0.0, 2.0.4, head of master branch, head of v2.1 branch. I've also reduced the testcase (the whole blob with busted, luarocks, penlight and other dependencies) to one file. I'll finish some more testing with different compilation flags and post it to luajit list.

**Comment by mpeterv** [comment] 2016-03-01 12:50
So, as expected, this is a duplicate of #369. Some workarounds are posted there.

**Comment by houqp** [comment] 2016-03-02 08:57
Hm... I think the problem now is the discussion in #369 is not documented. @Tieske is it possible to get this documented on the official documentation page?

For us, the workaround does not work. Most of our modules requires ffi, and it's not easier to put all of them into a helper.lua script. A cleaner way to fix it is to run each test in its own process...

**Comment by mpeterv** [comment] 2016-03-02 09:00
@houqp it should be enough to require just the FFI module in helper.lua, ignoring any other modules depending on it.

**Comment by houqp** [comment] 2016-03-02 09:03
@mpeterv I tried that, but got a bunch of redefined error in the cdef call [1], which is imported by some of the tests.

[1]: https://github.com/koreader/koreader-base/blob/master/ffi/util.lua#L10

**Comment by mpeterv** [comment] 2016-03-02 09:16
@houqp so busted drops and reloads that module, too. So, yes, you'll need to add all modules that can't be safely reloaded in helper.lua.

**Comment by houqp** [comment] 2016-03-02 17:58
That's why I said this workaround is not practical for us ;) Basically all our modules depends on FFI, that means we will have to put all of them in helper.lua...

**Comment by vsergeev** [comment] 2016-04-10 10:50
As a workaround, I've had good results running busted with the option `--no-auto-insulate`, e.g.

```
busted --lua=luajit --no-auto-insulate tests
```

This does sacrifice the test insulation feature of busted, but it seems to prevent the crash caused by the `ffi` module from being unanchored between tests.

**Comment by houqp** [comment] 2016-04-19 08:37
@vsergeev thanks! I can also confirm adding `--no-auto-insulate` fixes all our random segfaults :)

**Comment by houqp** [comment] 2016-04-19 08:38
I suggest we add this to the documentation.

**Comment by DorianGray** [comment] 2016-04-19 18:36
Alongside the documentation, I suggest we add a list of default preloaded libraries. We add common things that don't like to be reloaded, like ffi, by default, and allow users to add modules either in helper.lua or at the command line.

**Comment by houqp** [comment] 2016-04-20 23:43
yep, that will work too, as long as the behavior is documented :)

**Comment by Tieske** [comment] 2017-06-17 18:05
for reference, a possible fix: https://github.com/Olivine-Labs/luassert/pull/150

**Comment by Tieske** [comment] 2020-10-20 12:34
closing this, reloading ffi has been resolved

**Closed by Tieske** 2020-10-20 12:34 UTC
